name: eventsourcing
version: 0.1.0
dependencies:
  sqljocky:
    git: https://github.com/gwTumm/sqljocky.git
  http_server: any
  args: any
  path: any
  test: any
  crc32: ^0.1.6
  mime: ^0.9.3
  uuid: ^0.5.0
  retry: ^1.0.0
